GREEK_DICT = {
        'alpha':   'α',
        'beta':    'β',
        'gamma':   'γ',
        'delta':   'δ',
        'epsilon': 'ϵ',
        'zeta ':   'ζ',
        'eta  ':   'η',
        'theta':   'θ',
        'iota ':   'ι',
        'kappa':   'κ',
        'lambda':  'λ',
        'mu':      'μ',
        'nu':      'ν',
        'xi':      'ξ',
        'omicron': 'ο',
        'pi':      'π',
        'rho':     'ρ',
        'sigma':   'σ',
        'tau':     'τ',
        'upsilon': 'υ',
        'phi':     'ϕ',
        'chi':     'χ',
        'psi':     'ψ',
        'omega':   'ω',

        'Alpha':   'A',
        'Beta':    'B',
        'Gamma':   'Γ',
        'Delta':   'Δ',
        'Epsilon': 'E',
        'Zeta ':   'Z',
        'Eta  ':   'H',
        'Theta':   'Θ',
        'Iota ':   'I',
        'Kappa':   'K',
        'Lambda':  'Λ',
        'Mu':      'M',
        'Nu':      'N',
        'Xi':      'Ξ',
        'Omicron': 'O',
        'Pi':      'Π',
        'Rho':     'P',
        'Sigma':   'Σ',
        'Tau':     'T',
        'Upsilon': 'Υ',
        'Phi':     'Φ',
        'Chi':     'X',
        'Psi':     'Ψ',
        'Omega':   'Ω',
        }
